# permissions for end users to edit routerinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routerinstance-editor-role
rules:
- apiGroups:
  - kasico.world-direct.at
  resources:
  - routerinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kasico.world-direct.at
  resources:
  - routerinstances/status
  verbs:
  - get
