# permissions for end users to view routerinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: routerinstance-viewer-role
rules:
- apiGroups:
  - kasico.world-direct.at
  resources:
  - routerinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kasico.world-direct.at
  resources:
  - routerinstances/status
  verbs:
  - get
