apiVersion: kasico.world-direct.at/v1
kind: RouterInstance
metadata:
  name: routerinstance-sample
spec:
  ingressClassName: default
  templateConfigMapName: kamailio-templates
  kamailioImage: kamailio/kamailio:5.4.9-jessie 
  routerService:
    # https://github.com/kubernetes/kubernetes/pull/94028
    tcpPort: 0
    udpPort: 5060  
    annotations:
      metallb.universe.tf/address-pool: kamailio
      