apiVersion: kasico.world-direct.at/v1
kind: RouterInstance
metadata:
  name: routerinstance-sample
spec:
  ingressClassName: default
  routerService:
    annotations:
      metallb.universe.tf/address-pool: kamailio
      