apiVersion: kasico.world-direct.at/v1
kind: Ingress
metadata:
  name: ingress-sample
spec:
  ingressClassName: default
  rules:
  - sip: 
      domain: tenant1.sip.example.org
      headnumber: "+43512334455"
    backend:
      service:
        name: sip-server
