apiVersion: kasico.world-direct.at/v1
kind: Ingress
metadata:
  name: ingress-sample
spec:
  ingressClassName: default
  rules:
  - host: tenant1.sip.example.org
    backend:
      service:
        name: sip-server
